"use client"
import "./globals.css";
import Navbar from "@/components/ui/nav";
import { usePathname } from "next/navigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideNavbar = pathname === "/login" || pathname === "/login/auth";
  return (
    <html lang="en">
      <body>
      {!hideNavbar && <Navbar />}
        {children}
      </body>
    </html>
  );
}
